apiVersion: v2
name: probate-orchestrator-service
home: https://github.com/hmcts/probate-orchestrator-service
version: 1.0.24
description: HMCTS Probate Orchestrator Service
maintainers:
  - name: HMCTS Probate Team
    email: Probate@hmcts.net
dependencies:
  - name: java
    version: 3.7.7
    repository: '@hmctspublic'
