apiVersion: v2
name: probate-orchestrator-service
home: https://github.com/hmcts/probate-orchestrator-service
version: 1.0.9
description: HMCTS Probate Orchestrator Service
maintainers:
  - name: HMCTS Probate Team
    email: Probate@hmcts.net
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'