java:
  environment:
    LOG_LEVEL: DEBUG
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_NAME}.preview.platform.hmcts.net

keyVaults:
  probate:
    secrets:
      - name: launchdarkly-key
        alias: ld.sdk_key
      - name: launchdarklyUserkeyBackend
        alias: ld.user.key
